[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = ["cd ../.. && pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["cd ../.. && pnpm --filter @matrix-food/web build"]

[start]
cmd = "cd ../.. && pnpm --filter @matrix-food/web start"
